export const API_TRANSLATIONS: Record<string, string> = {
  '任务':'Tasks','任务与结果':'Tasks and results',
  '允许 AI 读取行情目录、自选、指标信息和当前图表，并按我的要求新增、修改和删除绘图；也可切换图表、管理自选、用户指标和我明确选择的本地数据连接，以及运行和保存用户任务。消息、查询结果、所需样本、任务结果及指定指标、接入文件或任务源码将发送给此服务（可能计费）':'Allow market/chart queries, requested drawings, chart navigation, watchlists, user indicators, explicitly selected data sources, and running/saving isolated user tasks. Messages, query results, required samples, task results and requested indicator/connector/task source are sent to this service (charges may apply).',
  '连接已恢复，无需重填 API Key。继续使用即允许查询行情、切换图表、管理自选、绘图、用户指标、已选择的数据连接及用户任务；查询结果、所需样本、任务结果及指定指标、接入文件或任务源码会发送至以下服务（可能计费）。':'Connection restored; the API key is retained. Continuing permits market queries, chart navigation, watchlists, drawings, user indicators, selected data sources and isolated user tasks. Required query/task results, samples and requested indicator/connector/task source are sent to this service (charges may apply).',
  '批量用户任务独立于当前图表，请在“任务”页面查看进度和停止。新对话或撤销连接会停止该会话的任务并释放结果。任务本地计算和导出不会调用模型；让 AI 分析结果时，所取分页会发送给所选服务。保存为工具只保存任务定义，重启不会自动运行。':'Batch tasks are independent of the current chart. View progress and stop them in Tasks. A new chat or revoked connection cancels that session’s jobs and releases results. Local computation/export does not call a model; pages requested for AI analysis go to the selected service. Saving a tool persists only its definition; restart does not run it automatically.',
  '用户任务编写说明':'User task SDK guide','检查用户任务':'Validate user task','开始批量任务':'Start batch task','查看我的运行任务':'List my tasks','查看任务进度':'Read task progress','读取任务结果分页':'Read task result page','停止我的任务':'Cancel my task','释放我的任务结果':'Release my task results','读取用户分享的任务结果':'Read explicitly shared results','我的任务工具':'My saved task tools','查看已保存任务代码':'Read saved task source','保存为我的任务工具':'Save reusable task tool','删除已保存的任务工具':'Remove saved task tool',
  '工具已更新或卸载，旧操作未继续；AI 将按最新工具重新判断。':'The tool changed or was removed. The old operation did not continue; the assistant will use the current catalog.',
  '当前工具目录达到资源预算，请停用不需要的扩展后重试。':'The tool catalog reached its resource budget. Disable unused extensions and retry.',
  '内容已被其他操作更新，请重新读取后再修改。':'The content changed. Read its latest state before editing again.',
  '本地保存失败，请检查可用空间后重试。':'Local saving failed. Check available storage and try again.',
  '指标未能正常运行，请读取诊断或修改后重试；其他指标可继续使用。':'The indicator could not run. Read its diagnostic or correct it and retry. Other indicators remain available.',
  '图表切换没有完成，请确认行情可用后重试。':'Chart navigation did not finish. Check market data availability and retry.',
  '操作失败且未能完整恢复，请检查当前内容后再继续。':'The operation failed and could not be fully restored. Check the current content before continuing.',
  '这个品种、参数或功能当前不可用，请先查询实际支持的能力。':'This symbol, parameter or feature is unavailable. Check the supported capabilities first.',
  '临时结果已过期或不属于当前会话，请重新获取。':'The temporary result expired or belongs to another session. Fetch it again.',
  '临时结果占用已满，请释放不用的结果后再试。':'Temporary result storage is full. Release unused results before trying again.',
  '上一项操作尚未结束，请稍后重试。':'The previous operation has not finished. Try again shortly.',
  '允许 AI 读取行情目录、自选、指标信息和当前图表，并按我的要求新增、修改和删除绘图；也可切换图表、管理自选和用户指标。消息、所需数据及指定用户指标源码将发送给此服务（可能计费）':'Allow market and chart queries, requested drawings, chart navigation, watchlist and user indicator management. Messages, required data and requested user indicator source are sent to this service (charges may apply).',
  '连接已恢复，无需重填 API Key。继续使用即允许查询行情、切换图表、管理自选、绘图和用户指标；所需数据及指定用户指标源码会发送至以下服务（可能计费）。':'Connection restored; no API key entry is needed. Continuing permits market queries, chart navigation, watchlist, drawing and user indicator management. Required data and requested indicator source are sent to this service (charges may apply).',
  '一个助手即可查询行情、切换图表、管理自选、绘图和用户指标，无需切换模式。用户指标在独立运行时验证与执行；不开放工程源码、任意文件、系统命令、凭据或下单权限。':'One assistant queries markets, navigates charts and manages watchlists, drawings and user indicators. User indicators are validated and executed in an isolated runtime. Application source, arbitrary files, system commands, credentials and trading are not available.',
  '查询自选报价':'Fetch watchlist quotes','加入自选':'Add to watchlist','移出自选':'Remove from watchlist','调整自选顺序':'Reorder watchlist',
  '读取当前图表':'Read current chart','打开品种':'Open symbol','切换周期':'Change period','切换复权':'Change adjustment','读取可见范围':'Read visible range','读取数据窗口':'Read data window',
  '添加指标':'Add indicator','移除指标':'Remove indicator','读取指标参数':'Read indicator inputs','修改指标参数':'Change indicator inputs','调整指标显示':'Set indicator visibility','重试指标':'Retry indicator',
  '读取指标编写说明':'Read indicator guide','读取指定用户指标源码':'Read requested user indicator source','验证用户指标':'Validate user indicator','保存用户指标':'Save user indicator','删除用户指标':'Delete user indicator',
  '一个助手即可查询行情目录、自选和指标信息，读取图表、计算和绘图，无需切换模式。也可查询其他品种的历史行情与报价，不会切换当前图表。不开放源码、系统命令、凭据或下单权限。':'One assistant queries catalogs, watchlists, indicator information and charts, calculates and draws without mode switching. It can also query other symbols’ history and quotes without switching your chart. Source, system, credential and trading access are not available.',
  '查询独立历史行情':'Query independent history', '读取行情结果分页':'Read market result page', '释放行情结果':'Release market result', '查询品种报价':'Query symbol quote', '批量查询报价':'Query quote batch',
  '继续使用已保存连接':'Continue with saved connection',
  '连接已恢复，无需重填 API Key。继续使用即允许读取行情目录、自选、指标信息和当前图表，并按要求修改绘图；所需数据会发送至以下服务（可能计费）。':'Connection restored; no API key entry is needed. Continuing allows catalog, watchlist, indicator and chart reads, plus requested drawing changes. Required data is sent to the following service (charges may apply).',
  '允许 AI 读取行情目录、自选、指标信息和当前图表，并按我的要求新增、修改和删除绘图；消息与所需数据将发送给此服务（可能计费）':'Allow AI to read the market catalog, watchlist, indicator information and current chart, and create, edit or delete drawings as requested. Messages and required data are sent to this service (charges may apply).',
  '一个助手即可查询行情目录、自选和指标信息，读取图表、计算和绘图，无需切换模式。按你的要求直接执行；不开放源码、系统命令、凭据或下单权限。':'One assistant queries catalogs, watchlists and indicators, reads charts, calculates and draws without mode switching. Requested actions run directly. Source code, system commands, credentials and trading are not available.',
  '读取行情源':'List market providers', '读取行情源详情':'Describe market provider', '读取品种目录':'Read symbol catalog', '搜索品种':'Search symbols',
  '读取自选列表':'Read watchlist', '读取指标定义':'Read indicator definitions', '读取当前指标':'Read current indicators', '读取用户指标库':'Read user indicator library',
  '连接已恢复，无需重填 API Key。继续使用即允许读取当前图表并按要求修改绘图，消息及所需数据会发送至以下服务（可能计费）。':'Connection restored; no API key entry is needed. Continuing allows chart reads and requested drawing changes. Messages and required data will be sent to the following service (charges may apply).',
  '模型只输出了工具调用文字，没有实际执行。可以直接继续提问，或检查当前模型是否支持标准工具调用。':'The model printed a tool call but did not execute it. You can continue chatting, or check whether this model supports standard tool calling.',
  '检测到模型连续重复执行相同工具且结果没有变化，已停止这一轮以避免死循环。可以直接继续提问，不需要新建会话。':'The model repeated the same tool with the same result, so this turn was stopped to prevent a loop. Continue in the same chat; no new conversation is needed.',
  '旧连接需重新保存，以启用完整图表助手。':'Save this older connection again to enable the complete chart assistant.',
  '正在恢复已保存连接':'Restoring saved connection',
  '确认使用连接':'Confirm connection',
  '连接已恢复，无需重填 Key。请在设置中确认使用。':'Connection restored. You do not need to re-enter the key. Confirm its use in Settings.',
  'Key 已保留，无需重填；留空保持不变':'Key retained. No need to re-enter it; leave blank to keep it.',
  '尚未连接 AI':'AI not connected','新对话':'New chat','历史':'History','历史对话':'Conversation history','暂无历史对话':'No saved conversations',
  '设置':'Settings','AI 设置':'AI settings','返回对话':'Back to chat','返回 AI 设置':'Back to AI settings',
  '历史对话保存在本机。重新打开历史后会重新绑定当前图表，不恢复旧图表权限，也不会自动重放以前的工具操作。':'Conversation history is stored locally. Reopening a chat binds it to the current chart with fresh authorization and never replays prior tool actions.',
  '手动切换图表只终止旧图表正在执行的那一轮；当前对话会保留，下一条消息自动使用新图表。停止不撤销已提交绘图，也不能保证撤回服务商已产生的费用。历史对话保存在本机。':'Manually switching charts stops only the in-flight turn for the old chart. The conversation stays open and the next message uses the new chart. Stopping does not undo committed drawings or provider charges. Conversation history is stored locally.',
  '已切换图表，当前对话已保留；下一条消息会使用新图表。':'Chart changed. This conversation is preserved; the next message will use the new chart.',
  '对话历史未能保存到本机':'Conversation history could not be saved locally.','对话历史读取失败':'Conversation history could not be loaded.',
  '这条历史对话已不可用':'This saved conversation is unavailable.','历史对话打开失败':'Could not open the saved conversation.',
  '有什么需要我帮你分析？':'What would you like to analyze?','连接你的 AI 服务后，即可开始对话。':'Connect your AI service to start a conversation.','连接 AI':'Connect AI',
  '待确认的图表操作':'Chart actions awaiting approval','继续本次任务':'Resume task','检查设置':'Check settings','发送消息，或描述你想分析的问题…':'Send a message or describe what you want to analyze…',
  '停止':'Stop','停止测试':'Stop test',
  'Enter 发送 · Shift + Enter 换行':'Enter to send · Shift + Enter for a new line',
  '选择服务商，填写模型和 API Key。连接细节会自动填写。':'Choose a provider, then enter a model and API key. Connection details are filled in automatically.',
  '服务商':'Provider','模型':'Model','自定义服务':'Custom service','通义千问':'Qwen',
  '粘贴 API Key；已连接时留空可保留':'Paste your API key; leave blank to keep a connected key',
  '记住连接，下次自动恢复（系统安全存储）':'Remember connection and restore next time (secure system storage)',
  '不勾选则仅本次使用。不会将 Key 明文保存在文件或聊天记录中。':'Otherwise use this session only. Keys are never saved as plain text in files or chat records.',
  '高级设置':'Advanced settings','连续无响应超时（秒）':'Inactivity timeout (seconds)',
  '持续收到数据不会因空闲超时被打断；异常卡死的单次网络请求仍有 2 小时进程保护时限。':'Receiving data resets the idle timeout. A stuck network request still has a two-hour process-safety deadline.',
  '允许 AI 读取当前图表并按我的要求新增、修改和删除绘图；消息与所需数据将发送给此服务（可能计费）':'Allow AI to read the current chart and create, edit or delete drawings as requested. Messages and required data are sent to this service (charges may apply).',
  '保存并返回对话':'Save and return to chat','连接管理与测试':'Connection management and testing','权限与会话说明':'Permissions and conversation details',
  '一个助手即可读取图表、计算和绘图，无需切换模式。按你的要求直接执行，范围包括已有绘图；不开放源码、系统命令、凭据或下单权限。':'One assistant reads, calculates and draws without mode switching. Requested actions run directly, including changes to existing drawings. Source code, system commands, credentials and trading are not available.',
  '连接外部 AI（MCP）':'Connect external AI (MCP)','供已经使用外部 AI 客户端的用户选择；内置聊天不需要配置。':'Optional for external AI clients. Built-in chat does not require this configuration.',
  '管理外部 AI 连接':'Manage external AI connections','直接提问，或让我读取图表、计算和绘图。':'Ask a question, or have me read the chart, calculate and draw.',
  '正在等待模型…':'Waiting for the model…','AI 正在思考…':'AI is thinking…','正在回复…':'Responding…',
  '记录已保留。可手动继续，不会重复执行已完成的绘图；重新请求可能计费。':'History is preserved. Resume manually without replaying completed drawings; another request may incur charges.',
  '记录已保留。可检查设置或新建对话；已提交的绘图不会自动撤销。':'History is preserved. Check settings or start a new chat. Committed drawings are not automatically undone.',
  '发送前请到设置中保存配置并允许连接。':'Before sending, save the configuration and allow the connection in Settings.',
  '此段回复未完成':'This response was interrupted',
  '读取图表上下文':'Read chart context','读取图表数据':'Read chart data','读取数据分页':'Read dataset page','区间统计':'Range statistics',
  '计算均线':'Calculate SMA','读取绘图类型':'List drawing types','生成绘图方案':'Prepare drawings','应用绘图':'Apply drawings','撤销本次绘图':'Undo drawing batch','完成':'Done',
  '修改已有绘图':'Edit existing drawings','撤销历史绘图':'Undo saved drawings','读取已有绘图':'Read existing drawings','读取绘图记录':'Read drawing history','释放数据快照':'Release dataset snapshot',
  '内存配置不会覆盖尚未读取的系统已保存配置；彻底删除请使用“清除配置与 Key”。':'A memory profile does not overwrite an unloaded saved profile. Use Forget configuration and key to delete it.',
  '内置 AI 对话': 'Built-in AI chat', '对话': 'Chat', '外部 MCP': 'External MCP', 'API 连接设置': 'API connection',
  '服务预设': 'Provider preset', '自定义': 'Custom', 'API 协议': 'API protocol', '完整请求地址（POST）': 'Full request URL (POST)',
  '模型 ID': 'Model ID', '填写服务商提供的模型 ID': 'Enter your provider’s model ID',
  '已配置时留空可保留；更换地址需重新输入': 'Leave blank to keep the key; enter it again for a different URL',
  '此服务不需要 Key': 'This service does not require a key', '保存到系统凭证库（macOS / Windows）': 'Remember in OS credential store (macOS / Windows)',
  '不勾选则仅保留在本次应用内存。Key 不写入项目、浏览器存储或对话记录。': 'Otherwise keep in app memory only. Keys are not saved in project files, browser storage or conversations.',
  '协议与资源选项': 'Protocol and resource options', '流式回复': 'Streaming', '工具调用': 'Tool calling',
  '请求流式用量统计（Chat 协议）': 'Request streaming usage (Chat protocol)', 'Chat 输出上限字段': 'Chat output limit field',
  '单次输出 Token 上限': 'Output token limit per request', '单次请求超时（秒）': 'Request timeout (seconds)',
  '允许本机或内网 IP 的明文 HTTP': 'Allow HTTP on local/private IP addresses',
  '明文 HTTP 不加密数据和 Key。公网地址仍必须使用 HTTPS。': 'HTTP does not encrypt data or keys. Public endpoints still require HTTPS.',
  '应用配置': 'Apply configuration', '读取已保存配置': 'Load saved configuration', '清除配置与 Key': 'Forget configuration and key',
  '尚未配置 API': 'API is not configured', '允许将此会话及授权数据发送到上述 API（可能计费）': 'Allow this conversation and authorized data to be sent to this API (charges may apply)',
  '测试连接与工具': 'Test connection and tools', '新建会话': 'New conversation',
  '测试只发送合成数据，最多调用模型三次。ChatGPT / Claude 订阅不会自动转为 API 额度。': 'Tests send synthetic data only, with up to three model calls. ChatGPT / Claude subscriptions do not automatically supply API credit.',
  '此会话的图表权限': 'Chart access for this conversation', '仅聊天，不读取图表': 'Chat only, no chart data',
  '分析：读取和计算': 'Analysis: read and compute', '对话记录': 'Conversation', '消息': 'Message',
  '描述任务，例如：统计最近 100 根 K 线的收盘价范围': 'Describe a task, such as finding the closing-price range of the latest 100 bars',
  '发送': 'Send', '停止当前任务': 'Stop task',
  '切换图表会终止旧图表任务。停止不撤销已提交绘图，也不能保证撤回服务商已产生的费用。会话仅保存在内存。': 'Switching charts stops the old chart task. Stopping does not undo committed drawings or refund provider charges. Conversations stay in memory only.',
  '配置未应用，发送前请保存': 'Unapplied changes: apply before sending', '正在保存配置': 'Saving configuration',
  '已配置（系统凭证库）': 'Configured (OS credential store)', '已配置（仅本次内存）': 'Configured (app memory only)',
  '没有已保存的配置': 'No saved configuration', '配置与 Key 已清除': 'Configuration and key cleared',
  '正在测试，仅发送合成数据': 'Testing with synthetic data only', '聊天与工具往返均通过': 'Chat and tool round trip passed',
  '聊天通过，工具调用尚未确认': 'Chat passed; tool calling not confirmed', '聊天通过，未测试工具': 'Chat passed; tools were not tested',
  '等待发送': 'Ready', '正在等待模型': 'Waiting for model', '正在执行工具': 'Running tool', '等待你确认图表修改': 'Awaiting your confirmation',
  '本轮完成': 'Turn completed', '已停止；已提交的绘图不会自动撤销': 'Stopped; committed drawings were not undone',
  '本轮已中断，请新建会话后继续。已提交的绘图不会自动撤销。': 'The turn was interrupted. Start a new conversation to continue. Committed drawings were not undone.',
  '输入 Token': 'Input tokens', '输出 Token': 'Output tokens', '未知': 'Unknown',
  '仅统计已完成请求，最终费用以服务商账单为准。': 'Completed requests only. Actual charges are determined by the provider.',
};
export const API_ERRORS: Record<string, string> = {
  tool_changed: '工具已更新或卸载，旧操作未继续；AI 将按最新工具重新判断。',
  registry_capacity: '当前工具目录达到资源预算，请停用不需要的扩展后重试。',
  state_conflict: '内容已被其他操作更新，请重新读取后再修改。',
  storage_failed: '本地保存失败，请检查可用空间后重试。',
  indicator_failed: '指标未能正常运行，请读取诊断或修改后重试；其他指标可继续使用。',
  navigation_failed: '图表切换没有完成，请确认行情可用后重试。',
  rollback_failed: '操作失败且未能完整恢复，请检查当前内容后再继续。',
  field_unavailable: '这个品种、参数或功能当前不可用，请先查询实际支持的能力。',
  snapshot_unavailable: '临时结果已过期或不属于当前会话，请重新获取。',
  snapshot_capacity: '临时结果占用已满，请释放不用的结果后再试。',
  busy: '上一项操作尚未结束，请稍后重试。',
  tool_call_text_only: '模型只输出了工具调用文字，没有实际执行。可以直接继续提问，或检查当前模型是否支持标准工具调用。',
  tool_loop_stopped: '检测到模型连续重复执行相同工具且结果没有变化，已停止这一轮以避免死循环。可以直接继续提问，不需要新建会话。',
  tool_repair_stopped: '模型连续生成相同的无效工具参数，已停止这一轮以避免反复报错。当前对话仍可继续，不需要新建会话。',
  authentication_failed: 'API Key 无效或未获授权。', access_denied: '此账户或网络区域无权访问该服务。',
  rate_or_quota_limit: '服务商限流或额度不足；没有自动重试。', endpoint_or_model_missing: '请检查完整 API 地址和模型 ID。',
  provider_rejected_request: '服务商拒绝了请求格式。请核对协议、Token 字段及流式用量选项。',
  provider_internal_error: '服务商返回内部错误（HTTP 500）。当前对话已保留，可稍后继续。',
  provider_bad_gateway: '服务商上游网关异常（HTTP 502）。当前对话已保留，可稍后继续。',
  provider_overloaded: '服务商当前繁忙或过载（HTTP 503/529）。当前对话已保留，可稍后继续。',
  provider_gateway_timeout: '服务商上游请求超时（HTTP 504）。当前对话已保留，可稍后继续。',
  provider_unavailable: '服务商返回 5xx 异常。当前对话已保留，可稍后继续。', network_error: '无法连接配置的 API。请检查网络和完整请求地址。',
  request_timeout: '服务商长时间没有返回数据，请检查网络或稍后继续。',
  request_deadline: '本次网络请求持续超过 2 小时且仍未结束，已停止该请求；已完成的本地操作不会重放。',
  model_output_limit: '回复达到长度上限，并非连接断开。可在高级设置提高输出上限后再试；未完成的工具没有执行。',
  redirect_blocked: 'API 返回了重定向，已阻止转发凭证。请填写最终请求地址。',
  secure_storage_unavailable: '系统凭证库不可用或未获许可，未降级为明文保存。', secure_storage_capacity: '配置超过系统凭证容量，请缩短配置或仅使用本次内存。',
  secure_storage_invalid: '已保存的配置损坏，未加载凭证。', endpoint_change_requires_key: '更换地址或协议时必须重新输入 Key，不能自动转用原凭证。',
  configuration_stale: '配置已变更或失效，请重新应用配置。', invalid_configuration: '请检查模型、地址、Token 上限和超时设置。',
  api_key_required: '请输入 API Key，或明确选择此服务不需要 Key。', invalid_api_key: 'Key 含无效字符或过长。',
  invalid_endpoint: 'API 地址不能含用户名、密码、查询参数或片段。', insecure_endpoint: '必须使用 HTTPS；本机/内网 IP 的 HTTP 需要明确启用。',
  cancelled: '已停止；已提交的绘图不会自动撤销', context_stale: '当前图表已变化，旧图表操作已终止；直接继续即可，下一条消息会重新绑定当前图表。',
  stream_incomplete: '模型流未完整结束，未执行未完成的工具调用。', stream_disconnected: '模型连接中断。',
  stream_mode_mismatch: '服务返回的流式模式与配置不一致，请调整选项后重试。', model_incomplete: '模型输出被截断或未正常完成，未执行工具。',
  unknown_tool: '模型请求了未开放的工具，已拒绝执行。', invalid_tool_call: '模型工具参数不完整或非法，已拒绝执行。',
  invalid_request: '请求参数未通过校验，本次工具未执行。',
  request_too_large: '单次模型请求异常巨大，已停止该请求以避免进程内存失控。',
  response_too_large: '模型返回了异常巨大的单次协议数据，已停止该请求以避免进程内存失控。',
  event_too_large: '模型返回了异常巨大的单个流式事件，已停止该请求以避免进程内存失控。',
  prompt_too_large: '单条消息超过 4 MiB；请改用文件或数据接口传递超大内容。',
};
